version: '3'

services:
  ui:
    build: ui
    ports:
      - "8080"
    environment:
      RECOMMENDERS: "random::recrnd:8090|tfidf::rectfidf:8091|lda::reclda:8092"

  recrnd:
    build: recommenders/random
    ports:
      - "8090"

  rectfidf:
    build: recommenders/tfidf
    ports:
      - "8091"

  reclda:
    build: recommenders/lda
    ports:
      - "8092"

  # db:
  #   image: postgres:10-alpine
  #   volumes:
  #     - "./volumes/db/pg_data:/var/lib/postgresql/data" # host-relative-path:path-within-container
